-- MySQL Script generated by MySQL Workbench
-- lun. 16 déc. 2019 11:48:45 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema paysan urban serre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paysan urban serre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paysan urban serre` DEFAULT CHARACTER SET utf8 ;
USE `paysan urban serre` ;

-- -----------------------------------------------------
-- Table `paysan urban serre`.`Client paysan urbain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paysan urban serre`.`Client paysan urbain` (
  `id_CPU` INT NOT NULL AUTO_INCREMENT,
  `CPU_id` VARCHAR(45) NULL,
  `CPU_nom` VARCHAR(45) NULL,
  `CPU_adresse` VARCHAR(45) NULL,
  `CPU_ville` VARCHAR(45) NULL,
  `CPU_tel` VARCHAR(45) NULL,
  `CPU_mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id_CPU`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paysan urban serre`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paysan urban serre`.`Commande` (
  `id_CO` INT NOT NULL AUTO_INCREMENT,
  `CO_ numéro` VARCHAR(45) NULL,
  `CO_date` DATE NULL,
  `CO_date_livraison` DATE NULL,
  `CO_prix_unitaire` INT NULL,
  `CO_prix totale` INT NULL,
  `Client payson urbain_id_CPU` INT NOT NULL,
  PRIMARY KEY (`id_CO`),
  INDEX `fk_Commande_Client payson urbain1_idx` (`Client payson urbain_id_CPU` ASC),
  CONSTRAINT `fk_Commande_Client payson urbain1`
    FOREIGN KEY (`Client payson urbain_id_CPU`)
    REFERENCES `paysan urban serre`.`Client paysan urbain` (`id_CPU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paysan urban serre`.`Fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paysan urban serre`.`Fournisseur` (
  `id_FR` INT NOT NULL AUTO_INCREMENT,
  `FR_nom` VARCHAR(45) NULL,
  `FR_adresse` VARCHAR(45) NULL,
  `FR_ville` VARCHAR(45) NULL,
  `FR_tel` VARCHAR(45) NULL,
  `FR_mail` VARCHAR(45) NULL,
  `Commande_id_CO` INT NOT NULL,
  PRIMARY KEY (`id_FR`, `Commande_id_CO`),
  INDEX `fk_Fournisseur_Commande1_idx` (`Commande_id_CO` ASC),
  CONSTRAINT `fk_Fournisseur_Commande1`
    FOREIGN KEY (`Commande_id_CO`)
    REFERENCES `paysan urban serre`.`Commande` (`id_CO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paysan urban serre`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paysan urban serre`.`Produit` (
  `id_PR` INT NOT NULL AUTO_INCREMENT,
  `PR_nom` VARCHAR(45) NULL,
  `PR_quantité` INT NULL,
  `Fournisseur_id_FR` INT NOT NULL,
  `Commande_id_CO` INT NOT NULL,
  PRIMARY KEY (`id_PR`),
  INDEX `fk_Produit_Fournisseur1_idx` (`Fournisseur_id_FR` ASC),
  INDEX `fk_Produit_Commande1_idx` (`Commande_id_CO` ASC),
  CONSTRAINT `fk_Produit_Fournisseur1`
    FOREIGN KEY (`Fournisseur_id_FR`)
    REFERENCES `paysan urban serre`.`Fournisseur` (`id_FR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Commande1`
    FOREIGN KEY (`Commande_id_CO`)
    REFERENCES `paysan urban serre`.`Commande` (`id_CO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
